SET tez.queue.name=Hive;
USE community_common;

DROP TABLE IF EXISTS hv_orc_tt_vmcontainermove_owner_base;

CREATE TABLE IF NOT EXISTS hv_orc_tt_vmcontainermove_owner_base (
    ownerorg_id int
,   ownerorgname string
,   customerorg_id int
,   customerorgname string
,   vmcontainermove_id int
,   carrierorg_id int
,   carriername string
,   carriergroup string
,   carriercluster string
,   lanecityname string
,   lanecityiata string
,   lanecityunlocode string
,   lanecitysubdivision string
,   lanecitycluster1 string
,   lanecitycluster2 string
,   lanecountryname string
,   laneregion1 string
,   laneregion2 string
,   polcity_id int
,   polcityname string
,   polcityiata string
,   polcityunlocode string
,   polcitylongitude string
,   polcitylatitude string
,   polcitysubdivision string
,   polcitycluster1 string
,   polcitycluster2 string
,   polcountry_id int
,   polcountryname string
,   polcountrycode string
,   polregion1 string
,   polregion2 string
,   podcity_id int
,   podcityname string
,   podcityiata string
,   podcityunlocode string
,   podcitylongitude string
,   podcitylatitude string
,   podcitysubdivision string
,   podcitycluster1 string
,   podcitycluster2 string
,   podcountry_id int
,   podcountryname string
,   podcountrycode string
,   podregion1 string
,   podregion2 string
,   origcity_id int
,   origcityname string
,   origcityiata string
,   origcityunlocode string
,   origcitylongitude string
,   origcitylatitude string
,   origcountry_id int
,   origcountryname string
,   origcountrycode string
,   origregion1 string
,   origregion2 string
,   destcity_id int
,   destcityname string
,   destcityiata string
,   destcityunlocode string
,   destcitylongitude string
,   destcitylatitude string
,   destcountry_id int
,   destcountryname string
,   destcountrycode string
,   destregion1 string
,   destregion2 string
,   transshipcity_id int
,   transshipcityname string
,   transshipcityiata string
,   transshipcityunlocode string
,   transshipcitylongitude string
,   transshipcitylatitude string
,   transshipcitysubdivision string
,   transshipcitycluster1 string
,   transshipcitycluster2 string
,   transshipcountry_id int
,   transshipcountryname string
,   transshipcountrycode string
,   transshipregion1 string
,   transshipregion2 string
,   transshipcityflag int
,   containertype_id int
,   containertype string
,   containertypecluster string
,   originmovetype_id int
,   originmovetype string
,   originmovetypecode string
,   originmovetypecluster string
,   originmovetypeclusterflag int
,   destinationmovetype_id int
,   destinationmovetype string
,   destinationmovetypecode string
,   destinationmovetypecluster string
,   destinationmovetypeclusterflag int
,   movetype_id int
,   movetype string
,   movetypecode string
,   movetypecluster string
,   containernum string
,   createtime timestamp
,   etdpol timestamp
,   etapod timestamp
,   atdpol timestamp
,   atapod timestamp
,   btdpol timestamp
,   btapod timestamp
,   booketdpol timestamp
,   booketapod timestamp
,   firstetd timestamp
,   firsteta timestamp
,   emptyoutgateoceantime timestamp
,   emptyoutgateinlandtime timestamp
,   offrailorigtime timestamp
,   fullingateoceantime timestamp
,   onboardpoltime timestamp
,   departpoltime timestamp
,   arrivetransshiptime timestamp
,   departtransshiptime timestamp
,   arrivepodtime timestamp
,   fullcontainerdischargetime timestamp
,   customsreleasedtime timestamp
,   fulloutgateoceantime timestamp
,   onraildesttime timestamp
,   emptycontainerreturntime timestamp
,   emptyoutgateattr timestamp
,   fullcontainerdeliveryattr timestamp
,   outforstuffingattr timestamp
,   yardinattr timestamp
,   yardoutattr timestamp
,   the_year int
,   the_year_quarter int
,   the_year_month int
,   the_year_week int
,   the_quarter int
,   the_quarter_name string
,   the_month int
,   the_month_name string
,   the_week int
,   the_week_name string
,   distance_km double
,   speed double
,   teu double
,   weight double
,   weightunit_id int
,   weight_kg double
,   volume double
,   volumeunit_id int
,   volume_cr double
,   capacityweight double
,   capacityweightunit_id int
,   capacityweight_kg double
,   capacityvolume double
,   capacityvolumeunit_id int
,   capacityvolume_cr double
,   etdpol_processed timestamp
,   booketdrec_processed timestamp
,   fullcontainerrec_processed timestamp
,   etdorigin_processed timestamp
,   polteu double
,   podteu double
,   polcontainer int
,   podcontainer int
,   poltimeliness double
,   podtimeliness double
,   fullcontainerrec_etdrec double
,   fullcontainerrec_etdrec_processed double
,   fullcontainerrec_etdorig_processed double
,   fullcontainerrec_etdorig double
,   atd_etdorigin double
,   first_booketdpol double
,   prev_booketdpol double
,   etd_booketdpol double
,   atd_booketdpol double
,   prev_firstetdpol double
,   atd_firstetdpol double
,   etd_prev_etdpol double
,   depart_prev_etdpol double
,   atd_prev_etdpol double
,   atd_departpoltime double
,   first_booketapod double
,   prev_booketapod double
,   ata_booketapod double
,   prev_firsteta double
,   ata_firsteta double
,   eta_prev_etapod double
,   arrived_prev_etapod double
,   ata_prev_etapod double
,   ata_arrivepodtime double
,   etadest_booketadel double
,   containerdelivery_booketadel double
,   atadest_booketadel double
,   booking_etd_pol_accuracy double
,   first_etd_pol_variance double
,   first_etd_pol_accuracy double
,   etd_pol_accuracy double
,   departure_time_diff double
,   book_eta_pod_variance double
,   book_eta_pod_accuracy double
,   first_eta_pod_accuracy double
,   first_eta_pod_variance double
,   eta_pod_accuracy double
,   arrival_time_differene double
,   vesseltransitestimate double
,   oceantransittime double
,   containertransittime double
,   containervesselestimatediff double
,   outforstripping double
,   outforstuffing double
,   customsreleased double
,   origininlandtransit double
,   destinationinlandtransit double
,   dwellawayfrompol double
,   dwellawayfrompod double
,   dwellatpol double
,   dwellatpod double
,   totalpoldwell double
,   totalpoddwell double
,   dwellattransship double
)
STORED AS ORC TBLPROPERTIES("orc.compress" = "SNAPPY")